# ---------- build stage ----------
FROM ubuntu:26.04 AS build

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get install -y --no-install-recommends dante-server \
 && rm -rf /var/lib/apt/lists/*

# ---------- runtime stage ----------
FROM ubuntu:26.04

LABEL org.opencontainers.image.authors="luth2" \
      org.opencontainers.image.description="Container with Dante Socks5 Proxy for Kubernetes" \
      org.opencontainers.image.source="https://github.com/luth2/DanteProxy" \
      org.opencontainers.image.version="1.0.0" \
      org.opencontainers.image.title="Dante Proxy Container"

# minimal runtime deps
RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates \
 && rm -rf /var/lib/apt/lists/*

# Non-root User
RUN groupadd -r dante && useradd -r -g dante -u 10001 dante

# binaries & libs
COPY --from=build /usr/sbin/danted /usr/sbin/danted
COPY --from=build /usr/lib /usr/lib
COPY --from=build /lib /lib

# runtime dirs
RUN mkdir -p /etc/danted /var/run/danted \
 && chown -R dante:dante /etc/danted /var/run/danted \
 && chmod 750 /etc/danted /var/run/danted

EXPOSE 1080
VOLUME ["/etc/danted"]

USER dante

HEALTHCHECK --interval=30s --timeout=3s \
  CMD ss -lnt | grep -q ':1080' || exit 1

CMD ["danted", "-f", "/etc/danted/danted.conf", "-D"]
